version: "3.1"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=jdbc:postgresql://postgres/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  config-server:
    image: config-server
    container_name: config-server
    build: ./
    environment:
      - CLOUD=http://config-server:8888
  app:
    container_name: springboot-clevertec
    image: springboot-clevertec
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - config-server
    restart: on-failure





