spring:
  cloud:
    config:
      import-check:
        enabled: false
      profile: prod
      uri:
        - htpp://localhost:8888

  application:
    name: clevertec-final-project

server:
  port: 8080
