spring:
  data:
    web:
      pageable:
        default-page-size: 10
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: postgres
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
sql:
  init:
    data-locations: data.sql
    mode: always