spring:
  application:
    name: config-server
  cloud:
    config:
      profile: dev
      server:
        git:
          uri: https://github.com/Saviour1231234/clevertec-final-project
server:
  port: 8888

