spring:
  data:
    web:
      pageable:
        default-page-size: 10
  datasource:
    url: ${POSTGRES_DB:jdbc:postgresql://postgres:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
sql:
  init:
    data-locations: data.sql
    mode: always